'use client';
import React,{useState,useEffect,useRef,useCallback} from 'react';
import {ScanLine,ClipboardList,Camera,Plus,Search,Download,ChevronRight,ChevronLeft,X,Check,RefreshCw,Clock,FileText,Barcode,ShieldCheck,LogOut,ArrowUpRight} from 'lucide-react';
import {statuses,blankOrder,orderCsv,type Order,type OrderInput} from '../lib/records';
import OrderCapture from '../components/OrderCapture';
import Batches from '../components/Batches';

export async function api(url:string,data:unknown):Promise<any>{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});let body:any;try{body=await response.json();}catch{throw new Error('The workspace could not respond. Check your connection, then retry.');}if(!response.ok)throw new Error(body.error||'The request could not be completed.');return body;}
export function download(name:string,text:string,type='text/csv;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);return <dialog ref={dialog} className={wide?'wide':''} aria-label={title} onCancel={e=>{e.preventDefault();onClose();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></div>{children}</dialog>;}
const statusClass=(s:string)=>s.toLowerCase().replaceAll(' ','-');
const dateText=(value:string)=>value?new Date(value+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}):'—';

export default function Studio({userName}:{userName:string}){
  const [view,setView]=useState('orders'),[orders,setOrders]=useState<Order[]>([]),[counts,setCounts]=useState<any[]>([]),[total,setTotal]=useState(0),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[offset,setOffset]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState<Order|OrderInput|null>(null),[history,setHistory]=useState<any[]>([]);
  const [capture,setCapture]=useState(false),[due,setDue]=useState('all');
  const revision=useRef(0);
  const refresh=useCallback(async()=>{const request=++revision.current;setLoading(true);try{const result=await api('/api/orders',{action:'search',query,status,offset,due,today:new Date().toLocaleDateString('en-CA')});if(request===revision.current){setOrders(result.orders);setCounts(result.counts);setTotal(result.total);setError('');}}catch(e){if(request===revision.current)setError((e as Error).message);}finally{if(request===revision.current)setLoading(false);}},[query,status,offset,due]);
  useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();const register=(tool:any)=>{try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}};
    register({name:'filter_patient_orders',description:'Show patient orders matching the search and status in this private workspace. Returns the number shown and total matches; does not modify records.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:160},status:{type:'string',enum:['all',...statuses]}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['query','status'].includes(k))||(input.query!==undefined&&(typeof input.query!=='string'||input.query.length>160))||(input.status!==undefined&&!['all',...statuses].includes(input.status)))throw new Error('Use a query string and a supported status.');const q=input.query||'',s=input.status||'all',result=await api('/api/orders',{action:'search',query:q,status:s});setView('orders');setQuery(q);setStatus(s);setDue('all');setOffset(0);setOrders(result.orders);setCounts(result.counts);setTotal(result.total);return {shown:result.orders.length,total:result.total,query:q,status:s};}});
    register({name:'start_order_capture',description:'Open the paper capture flow. Camera permission and saving each reviewed order remain explicit user actions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No inputs are required.');setView('orders');setCapture(true);return {opened:'Capture patient orders',saved:false};}});return()=>controller.abort();},[]);
  useEffect(()=>{const timer=setTimeout(refresh,200);return()=>clearTimeout(timer);},[refresh]);
  useEffect(()=>{const timer=setInterval(()=>{if(!document.hidden)refresh();},30000);return()=>clearInterval(timer);},[refresh]);
  useEffect(()=>{if(notice){const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);}},[notice]);
  async function openOrder(order:Order){setEditing(order);setHistory([]);try{setHistory((await api('/api/orders',{action:'history',id:order.id})).history);}catch{setHistory([{message:'History is temporarily unavailable.'}]);}}
  const count=(s:string)=>Number(counts.find(c=>c.status===s)?.count||0),active=counts.reduce((n,c)=>n+(c.status==='Picked up'?0:Number(c.count)),0);
  return <div className="studio-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark"><ScanLine/></span><span>FrameScan<small>ORDER STUDIO</small></span></a><div className="nav-label">WORKSPACE</div><nav><button className={view==='orders'?'selected':''} onClick={()=>setView('orders')}><ClipboardList/>Patient orders</button><button className={view==='upcs'?'selected':''} onClick={()=>setView('upcs')}><Barcode/>Frame UPC batches</button></nav><div className="sidebar-bottom"><ShieldCheck/><span>Private workspace<small>Saved across your devices</small></span></div></aside>
    <div className="main-shell"><header className="topbar"><span>Havertown <ChevronRight size={15}/> {view==='orders'?'Patient orders':'Frame UPC batches'}</span><div className="account"><span className="avatar">{userName.slice(0,1).toUpperCase()}</span><span>{userName}</span><a href="/signout-with-chatgpt?return_to=/" aria-label="Sign out"><LogOut size={17}/></a></div></header>
    <main><div className="page-heading"><div><div className="eyebrow">YOUR DAILY WORKSPACE</div><h1>{view==='orders'?'Patient orders':'Frame UPC batches'}</h1><p>{view==='orders'?'From paper order to pickup. Keep every step in view.':'Collect frame codes, then move through Encompass one at a time.'}</p></div>{view==='orders'&&<div className="heading-actions"><button className="button" onClick={()=>{setEditing(blankOrder());setHistory([]);}}><Plus/>New order</button><button className="button primary" onClick={()=>setCapture(true)}><Camera/>Capture papers</button></div>}</div>
    {view==='orders'?<><div className="stat-grid"><button onClick={()=>{setStatus('all');setOffset(0);}}><span>Open orders</span><strong>{active}</strong><ClipboardList/></button><button onClick={()=>{setStatus('At lab');setOffset(0);}}><span>At the lab</span><strong>{count('At lab')}</strong><Clock/></button><button onClick={()=>{setStatus('Ready');setOffset(0);}}><span>Ready for pickup</span><strong>{count('Ready')}</strong><Check/></button><button onClick={()=>{setStatus('On hold');setOffset(0);}}><span>Needs attention</span><strong>{count('On hold')}</strong><FileText/></button></div>
    <div className="due-filters" role="group" aria-label="Due date filters">{[["all","All dates"],["today","Due today"],["overdue","Overdue"]].map(([value,label])=><button key={value} aria-pressed={due===value} onClick={()=>{setDue(value);setOffset(0);}}>{label}</button>)}</div><section className="records-panel"><div className="panel-toolbar"><div className="search-field"><Search size={18}/><input aria-label="Search patient orders" placeholder="Search patient, order number, or UPC" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></div><select aria-label="Filter order status" value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="all">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="button quiet" onClick={refresh} aria-label="Refresh orders"><RefreshCw size={18}/></button><button className="button quiet" onClick={async()=>{try{download('patient-orders.csv',orderCsv((await api('/api/orders',{action:'export'})).orders));}catch(e){setError((e as Error).message);}}}><Download size={17}/>Export</button></div>
    {error&&<div className="error" role="alert">{error}<button onClick={refresh}>Retry</button></div>}
    <div className="table-scroll"><table><thead><tr><th>Patient / order</th><th>Frame UPC</th><th>Due date</th><th>Status</th><th>Last updated</th><th><span className="sr-only">Open order</span></th></tr></thead><tbody>{orders.map(order=><tr key={order.id} onClick={()=>openOrder(order)}><td><button className="row-link" onClick={e=>{e.stopPropagation();openOrder(order);}}>{order.patient}</button><small>{order.reference||'No order number'}{order.lab?' · '+order.lab:''}</small></td><td className="digits">{order.upc||'—'}</td><td><span className={order.dueOn&&order.dueOn<new Date().toLocaleDateString('en-CA')&&!['Ready','Picked up'].includes(order.status)?'overdue':''}>{dateText(order.dueOn)}</span></td><td><span className={'status-badge '+statusClass(order.status)}>{order.status}</span></td><td>{new Date(order.updatedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</td><td><ChevronRight size={18}/></td></tr>)}</tbody></table></div>
    {!orders.length&&!loading&&!error&&<div className="empty-state"><span className="empty-icon"><ClipboardList size={34}/></span><h2>{query||status!=='all'?'No matching orders':'A clear view of every order'}</h2><p>{query||status!=='all'?'Try another name, order number, or status.':'Add your first patient order. Details and status updates will be saved together.'}</p>{!query&&status==='all'&&<button className="button primary" onClick={()=>setEditing(blankOrder())}><Plus size={18}/>Add an order</button>}</div>}
    <footer className="table-footer"><span>{loading?'Loading orders…':`${total.toLocaleString()} orders${total>100?` · Showing ${offset+1}–${Math.min(offset+100,total)}`:''}`}</span><div><button className="icon-button" disabled={offset===0} aria-label="Previous page" onClick={()=>setOffset(v=>Math.max(0,v-100))}><ChevronLeft/></button><button className="icon-button" disabled={offset+100>=total} aria-label="Next page" onClick={()=>setOffset(v=>v+100)}><ChevronRight/></button></div></footer></section></>:<Batches/>}
    {capture&&<OrderCapture onClose={()=>setCapture(false)} onSaved={refresh}/>}<div className="workspace-note"><ShieldCheck size={16}/>Only reviewed order details are saved. Camera images are processed on your device.</div></main></div>
    {notice&&<div className="toast" role="status"><Check size={19}/>{notice}</div>}
    {editing&&<OrderEditor value={editing} history={history} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);setNotice('Order saved');refresh();}}/>}
  </div>;
}

export function OrderEditor({value,history,onClose,onSaved,children,saveLabel='Save order'}:{value:Order|OrderInput;history:any[];onClose:()=>void;onSaved:()=>void;children?:React.ReactNode;saveLabel?:string}){
  const [draft,setDraft]=useState(value),[saving,setSaving]=useState(false),[error,setError]=useState('');const id=useRef('id' in value?value.id:crypto.randomUUID());
  const field=(name:keyof OrderInput)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>setDraft(v=>({...v,[name]:e.target.value}));
  async function save(e:React.FormEvent){e.preventDefault();if(saving)return;setSaving(true);setError('');try{await api('/api/orders',{action:'id' in value?'update':'create',id:id.current,version:'version' in value?value.version:undefined,order:draft});onSaved();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  return <Modal title={'id' in value?'Order details':'Review patient order'} onClose={()=>{if(!saving)onClose();}} wide={!!children}><form onSubmit={save}>{children}<p className="form-intro">Check the details against the paper before saving.</p><div className="form-grid"><label className="full">Patient name<input autoFocus required maxLength={160} value={draft.patient} onChange={field('patient')} autoComplete="off"/></label><label>Order number<input maxLength={100} value={draft.reference} onChange={field('reference')} autoComplete="off"/></label><label>Status<select value={draft.status} onChange={field('status')}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Frame UPC<input inputMode="numeric" maxLength={14} value={draft.upc} onChange={field('upc')} autoComplete="off"/></label><label>Lab<input maxLength={160} value={draft.lab} onChange={field('lab')}/></label><label>Ordered on<input type="date" value={draft.orderedOn} onChange={field('orderedOn')}/></label><label>Expected / due<input type="date" value={draft.dueOn} onChange={field('dueOn')}/></label><label className="full">Notes<textarea rows={3} maxLength={3000} value={draft.notes} onChange={field('notes')} placeholder="Order notes, exceptions, or next steps"/></label></div>{error&&<p className="error" role="alert">{error}</p>}{history.length>0&&<details className="history"><summary>Status history</summary>{history.map((item,i)=><div key={i}><span>{item.message}</span><small>{item.createdAt?new Date(item.createdAt).toLocaleString():''}</small></div>)}</details>}<div className="modal-actions"><button type="button" className="button" onClick={onClose} disabled={saving}>Cancel</button><button className="button primary" disabled={saving}><Check size={18}/>{saving?'Saving…':saveLabel}</button></div></form></Modal>;
}



